services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Eco4d
    ports:
      - "5432:5432"
    restart: unless-stopped